//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaOYomu
{
    using System;
    using System.Collections.Generic;
    
    public partial class MangaTitleGenres
    {
        public int MangaTitleGenresID { get; set; }
        public Nullable<int> MangaTitleID { get; set; }
        public Nullable<int> GenresID { get; set; }
    
        public virtual Genres Genres { get; set; }
        public virtual MangaTitle MangaTitle { get; set; }
    }
}
