//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaOYomu
{
    using System;
    using System.Collections.Generic;
    
    public partial class MangaTitle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MangaTitle()
        {
            this.Chapters = new HashSet<Chapters>();
            this.MangaTitleGenres = new HashSet<MangaTitleGenres>();
        }
    
        public int MangaTitleID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Cover { get; set; }
        public Nullable<int> MangaTypeID { get; set; }
        public Nullable<int> TitleStatusID { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public Nullable<int> AgeStatusID { get; set; }
    
        public virtual AgeStatus AgeStatus { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chapters> Chapters { get; set; }
        public virtual MangaType MangaType { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual TitleStatus TitleStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MangaTitleGenres> MangaTitleGenres { get; set; }
    }
}
