//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaOYomu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MangaOYomuDBEntities : DbContext
    {
        public MangaOYomuDBEntities()
            : base("name=MangaOYomuDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgeStatus> AgeStatus { get; set; }
        public virtual DbSet<Artist> Artist { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Chapters> Chapters { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<MangaTitle> MangaTitle { get; set; }
        public virtual DbSet<MangaTitleGenres> MangaTitleGenres { get; set; }
        public virtual DbSet<MangaType> MangaType { get; set; }
        public virtual DbSet<Pages> Pages { get; set; }
        public virtual DbSet<Publisher> Publisher { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TitleStatus> TitleStatus { get; set; }
    }
}
