//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaOYomu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        public int PagesID { get; set; }
        public string Image { get; set; }
        public Nullable<int> ChaptersID { get; set; }
    
        public virtual Chapters Chapters { get; set; }
    }
}
